site_name: HIT萌新灯塔计划
site_author: YellowPeach
site_description: >-
  萌新灯塔

repo_name: Newcomer-s-Guide-to-HIT
repo_url: https://github.com/turturturturtur/Newcomer-s-Guide-to-HIT

copyright:
  Copyright &copy; 2023 <a href="https://github.com/turturturturtur" target="_blank" rel="noopener">YellowPeach</a>


theme:
  name: material
  custom_dir: overrides  #主要是这一行
#  logo: static/images/title.png
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.selections
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.code.annoation
    - content.code.copy
    - toc.follow
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/turturturturtur/Newcomer-s-Guide-to-HIT
  analytics:
    provider: google
    property: G-KJB4RXSKZG

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - footnotes

nav:
  - 前言: "index.md"
  - 政策: "政策.md"
  - 工大电子系统: "工大电子系统/工大电子系统介绍.md"
  - 综合素质: 
    - 介绍: "综合素质/综素.md"
    - 练习场所: "综合素质/场所.md"
  - 学业:
    - 工大公益计划一览: "学业/工大著名公益计划/公益计划介绍.md"
    - 必学工具: "学业/必学工具/必学工具.md"
    - 老师推荐: "学业/老师风评.md"
    - 服务:
      - 一校区: "学业/学业服务/学业服务.md"
    - CS（计算机科学技术）:
      - 网站推荐: "学业/CS/CS网站推荐.md"
      - 论坛推荐: "学业/CS/CS论坛推荐.md"
  - 竞赛:
    - 竞赛: "竞赛/竞赛.md"
  - 升学:
    - 关于升学的一些看法: "升学/综述.md"
    - 保研本校: "升学/保研本校/保内规划.md"
    - 保研外校: "升学/保研外校/保外规划.md"
    - 考研: "升学/考研/考研规划.md"
  - 创业:
    - "创业/创业介绍.md"
  - 投稿须知: "投稿.md"
  - 后记: "后记.md"

      
  